import { NextResponse } from "next/server";
import { z } from "zod";
import { getApiProfile } from "@/lib/api-auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { assertSameOrigin, siteUrl } from "@/lib/utils";
const createSchema = z.object({ nome: z.string().trim().min(2).max(160), email: z.string().email().max(254), perfil: z.enum(["administrator", "employee"]) });
const actionSchema = z.object({ id: z.string().uuid(), action: z.enum(["activate", "deactivate", "reset"]) });
export async function POST(request: Request) { try { assertSameOrigin(request); const actor = await getApiProfile(); if (!actor || actor.perfil !== "administrator") return NextResponse.json({ error: "Acesso restrito" }, { status: 403 }); const parsed = createSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Revise os dados do funcionário." }, { status: 400 }); const admin = createAdminClient(); const email = parsed.data.email.toLowerCase(); const { data, error } = await admin.auth.admin.inviteUserByEmail(email, { data: { nome: parsed.data.nome, perfil: parsed.data.perfil }, redirectTo: `${siteUrl()}/auth/callback?next=/atualizar-senha` }); if (error || !data.user) return NextResponse.json({ error: "Não foi possível criar o acesso. Verifique se o e-mail já está cadastrado." }, { status: 400 }); const { error: profileError } = await admin.from("profiles").insert({ user_id: data.user.id, nome: parsed.data.nome, email, perfil: parsed.data.perfil, ativo: true }); if (profileError) { await admin.auth.admin.deleteUser(data.user.id); throw profileError; } await admin.from("audit_logs").insert({ user_id: actor.id, action: "create_staff_user", entity_type: "profile", metadata: { created_user_id: data.user.id, role: parsed.data.perfil } }); return NextResponse.json({ ok: true }, { status: 201 }); } catch { return NextResponse.json({ error: "Não foi possível criar o funcionário." }, { status: 500 }); } }
export async function PATCH(request: Request) { try { assertSameOrigin(request); const actor = await getApiProfile(); if (!actor || actor.perfil !== "administrator") return NextResponse.json({ error: "Acesso restrito" }, { status: 403 }); const parsed = actionSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Ação inválida" }, { status: 400 }); if (parsed.data.id === actor.id && parsed.data.action === "deactivate") return NextResponse.json({ error: "Você não pode desativar seu próprio usuário." }, { status: 400 }); const admin = createAdminClient(); const { data: target } = await admin.from("profiles").select("id,user_id,email").eq("id", parsed.data.id).maybeSingle(); if (!target) return NextResponse.json({ error: "Usuário não encontrado" }, { status: 404 }); if (parsed.data.action === "reset") await admin.auth.resetPasswordForEmail(target.email, { redirectTo: `${siteUrl()}/auth/callback?next=/atualizar-senha` }); else await admin.from("profiles").update({ ativo: parsed.data.action === "activate" }).eq("id", target.id); await admin.from("audit_logs").insert({ user_id: actor.id, action: `staff_${parsed.data.action}`, entity_type: "profile", entity_id: target.id, metadata: {} }); return NextResponse.json({ ok: true }); } catch { return NextResponse.json({ error: "Não foi possível atualizar o funcionário." }, { status: 500 }); } }
