"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, MailPlus, Power, RotateCcw } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import type { ProfileRow } from "@/types/database";

export function UserManagement({ users }: { users: ProfileRow[] }) {
  const router = useRouter(); const [loading, setLoading] = useState(""); const [nome, setNome] = useState(""); const [email, setEmail] = useState(""); const [perfil, setPerfil] = useState<"administrator" | "employee">("employee");
  async function api(method: string, body: unknown) { const response = await fetch("/api/admin/users", { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Ação não concluída."); }
  async function invite(event: React.FormEvent) { event.preventDefault(); setLoading("invite"); try { await api("POST", { nome, email, perfil }); toast.success("Convite enviado ao funcionário."); setNome(""); setEmail(""); setPerfil("employee"); router.refresh(); } catch (e) { toast.error(e instanceof Error ? e.message : "Erro"); } finally { setLoading(""); } }
  async function action(id: string, action: "activate" | "deactivate" | "reset") { if (action === "deactivate" && !window.confirm("Desativar este usuário? O acesso será bloqueado imediatamente nas próximas requisições.")) return; setLoading(`${action}:${id}`); try { await api("PATCH", { id, action }); toast.success(action === "reset" ? "E-mail de recuperação solicitado." : "Usuário atualizado."); router.refresh(); } catch (e) { toast.error(e instanceof Error ? e.message : "Erro"); } finally { setLoading(""); } }
  return <div className="space-y-6"><form onSubmit={invite} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-semibold"><MailPlus size={20} />Convidar funcionário</h2><p className="mt-1 text-sm text-slate-500">O funcionário receberá um e-mail para definir a senha. Não existe cadastro público.</p><div className="mt-5 grid gap-4 md:grid-cols-3"><div><label className="mb-1.5 block text-sm font-semibold" htmlFor="staff-name">Nome</label><Input id="staff-name" value={nome} onChange={(e) => setNome(e.target.value)} required minLength={2} /></div><div><label className="mb-1.5 block text-sm font-semibold" htmlFor="staff-email">E-mail</label><Input id="staff-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><div><label className="mb-1.5 block text-sm font-semibold" htmlFor="staff-role">Perfil</label><select id="staff-role" value={perfil} onChange={(e) => setPerfil(e.target.value as typeof perfil)} className="h-12 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="employee">Funcionário</option><option value="administrator">Administrador</option></select></div></div><Button className="mt-4" disabled={loading === "invite"}>{loading === "invite" ? <Loader2 className="animate-spin" /> : <MailPlus />}Enviar convite</Button></form><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold">Usuários cadastrados</h2></div><div className="divide-y divide-slate-100">{users.map((user) => <div key={user.id} className="grid gap-4 px-5 py-4 md:grid-cols-[minmax(0,1fr)_170px_130px_230px] md:items-center"><div><p className="font-semibold">{user.nome}</p><p className="mt-1 text-sm text-slate-500">{user.email}</p></div><div><Badge tone={user.perfil === "administrator" ? "info" : "neutral"}>{user.perfil === "administrator" ? "Administrador" : "Funcionário"}</Badge></div><div><Badge tone={user.ativo ? "success" : "danger"}>{user.ativo ? "Ativo" : "Desativado"}</Badge></div><div className="flex flex-wrap justify-end gap-2"><Button size="sm" variant="ghost" onClick={() => action(user.id, "reset")} disabled={Boolean(loading)}><RotateCcw size={16} />Redefinir acesso</Button><Button size="sm" variant={user.ativo ? "danger" : "secondary"} onClick={() => action(user.id, user.ativo ? "deactivate" : "activate")} disabled={Boolean(loading)}><Power size={16} />{user.ativo ? "Desativar" : "Ativar"}</Button></div></div>)}</div></div></div>;
}
